// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function AddPostgresConnection(arg1:model.Postgres):Promise<boolean>;

export function EstablishPostgresConnection(arg1:number,arg2:string):Promise<any>;

export function ExecuteQuery(arg1:number,arg2:string,arg3:Array<any>):Promise<model.GenericResponse>;

export function GetAllTables(arg1:number):Promise<Array<any>>;

export function GetPostgresConnections():Promise<Array<model.Postgres>>;

export function GetPostgresServerDatabases(arg1:number):Promise<Array<any>>;

export function GetSqlite3Version():Promise<string>;

export function TerminatePostgresConnection(arg1:number):Promise<boolean>;

export function TestConnectPostgres(arg1:model.Postgres):Promise<boolean>;
