// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPostgresConnection(arg1) {
  return window['go']['app']['Connections']['AddPostgresConnection'](arg1);
}

export function EstablishPostgresConnection(arg1) {
  return window['go']['app']['Connections']['EstablishPostgresConnection'](arg1);
}

export function EstablishPostgresDatabaseConnection(arg1, arg2, arg3) {
  return window['go']['app']['Connections']['EstablishPostgresDatabaseConnection'](arg1, arg2, arg3);
}

export function ExecuteQuery(arg1, arg2, arg3) {
  return window['go']['app']['Connections']['ExecuteQuery'](arg1, arg2, arg3);
}

export function GetAllPostgresTables(arg1) {
  return window['go']['app']['Connections']['GetAllPostgresTables'](arg1);
}

export function GetPostgresConnections() {
  return window['go']['app']['Connections']['GetPostgresConnections']();
}

export function GetPostgresServerDatabases(arg1, arg2, arg3) {
  return window['go']['app']['Connections']['GetPostgresServerDatabases'](arg1, arg2, arg3);
}

export function GetSqlite3Version() {
  return window['go']['app']['Connections']['GetSqlite3Version']();
}

export function TerminatePostgresConnection(arg1) {
  return window['go']['app']['Connections']['TerminatePostgresConnection'](arg1);
}

export function TestConnectPostgres(arg1) {
  return window['go']['app']['Connections']['TestConnectPostgres'](arg1);
}
