// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportRows(arg1, arg2, arg3, arg4) {
  return window['go']['app']['Export']['ExportRows'](arg1, arg2, arg3, arg4);
}

export function ExportTable(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['app']['Export']['ExportTable'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}
