// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function ExportRows(arg1:string,arg2:string,arg3:Array<string>,arg4:Array<any>):Promise<model.ExportResult>;

export function ExportTable(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<model.ExportResult>;
