// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTab(arg1, arg2) {
  return window['go']['app']['Tabs']['AddTab'](arg1, arg2);
}

export function DeleteTab(arg1) {
  return window['go']['app']['Tabs']['DeleteTab'](arg1);
}

export function GetAllTabs() {
  return window['go']['app']['Tabs']['GetAllTabs']();
}

export function SetActiveTab(arg1) {
  return window['go']['app']['Tabs']['SetActiveTab'](arg1);
}

export function UpdateTabEditorContent(arg1, arg2) {
  return window['go']['app']['Tabs']['UpdateTabEditorContent'](arg1, arg2);
}
