// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function AddTab(arg1:number,arg2:string):Promise<model.Tab>;

export function DeleteTab(arg1:number):Promise<model.Tab>;

export function GetAllTabs():Promise<Array<model.Tab>>;

export function SetActiveTab(arg1:number):Promise<model.Tab>;

export function UpdateTabEditorContent(arg1:number,arg2:string):Promise<void>;
