package app

// Column-type tests. The grid's header icons are driven by the type postgres
// reports for each column of a result set, which is resolved by a catalog query
// against the live server -- so, like the schema editor's SQL, it can only be
// checked against a real one. Same harness, same skip: see table_schema_test.go.

import (
	"dbmx/model"
	"testing"
)

func TestLiveQueryColumnTypes(t *testing.T) {
	c, cleanup := liveConnections(t)
	defer cleanup()

	exec(t, c, `DROP TABLE IF EXISTS specimens, keepers, readings CASCADE`)
	exec(t, c, `DROP TYPE IF EXISTS temper CASCADE`)
	exec(t, c, `CREATE TYPE temper AS ENUM ('calm', 'testy')`)
	exec(t, c, `CREATE TABLE keepers (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)`)
	exec(t, c, `CREATE TABLE specimens (
		id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		name text NOT NULL,
		label character varying(50),
		price numeric(10,2),
		shipped boolean,
		seen_on date,
		seen_at timestamp with time zone,
		took interval,
		ref uuid,
		payload jsonb,
		tags text[],
		mood temper,
		blob bytea,
		origin inet,
		keeper_id integer REFERENCES keepers (id)
	)`)

	// What the frontend keys its header off: the name postgres prints for the
	// type, the short name the header shows, and the catalog category behind the
	// icon. Nullability rides along because it is a property of the column, not
	// of the type.
	want := []struct {
		name        string
		dataType    string
		displayType string
		category    string
		nullable    bool
	}{
		{"id", "integer", "int4", "N", false},
		{"name", "text", "text", "S", false},
		{"label", "character varying", "varchar", "S", true},
		{"price", "numeric", "numeric", "N", true},
		{"shipped", "boolean", "bool", "B", true},
		{"seen_on", "date", "date", "D", true},
		{"seen_at", "timestamp with time zone", "timestamptz", "D", true},
		{"took", "interval", "interval", "T", true},
		{"ref", "uuid", "uuid", "U", true},
		{"payload", "jsonb", "jsonb", "U", true},
		{"tags", "text[]", "text[]", "A", true},
		{"mood", "temper", "temper", "E", true},
		{"blob", "bytea", "bytea", "U", true},
		{"origin", "inet", "inet", "I", true},
		{"keeper_id", "integer", "int4", "N", true},
	}

	assertTypes := func(t *testing.T, columnTypes []model.ColumnType) {
		t.Helper()
		if len(columnTypes) != len(want) {
			t.Fatalf("got %d column types, want %d", len(columnTypes), len(want))
		}
		for i, w := range want {
			got := columnTypes[i]
			if got.Name != w.name || got.DataType != w.dataType || got.DisplayType != w.displayType || got.Category != w.category {
				t.Errorf("column %d = {%q %q %q %q}, want {%q %q %q %q}",
					i, got.Name, got.DataType, got.DisplayType, got.Category,
					w.name, w.dataType, w.displayType, w.category)
			}
			if got.IsNullable != w.nullable {
				t.Errorf("column %q nullable = %v, want %v", w.name, got.IsNullable, w.nullable)
			}
		}
	}

	t.Run("a query reports the type of every column", func(t *testing.T) {
		result := c.ExecuteQuery(liveTabID, `SELECT * FROM specimens`, false)
		if !result.OK {
			t.Fatalf("query failed: %s", result.Message)
		}
		assertTypes(t, result.ColumnTypes)
	})

	t.Run("the second query answers from the cache", func(t *testing.T) {
		// Every oid is cached by now, so this one resolves without touching
		// pg_catalog again -- and must still come back with the same types.
		result := c.ExecuteQuery(liveTabID, `SELECT * FROM specimens`, false)
		if !result.OK {
			t.Fatalf("query failed: %s", result.Message)
		}
		assertTypes(t, result.ColumnTypes)
	})

	t.Run("the table view reports them too", func(t *testing.T) {
		result := c.GetTableData(liveTabID, "specimens", "", "20", "0", "", "", "", false)
		if !result.OK {
			t.Fatalf("table data failed: %s", result.Message)
		}
		assertTypes(t, result.ColumnTypes)
	})

	t.Run("a projection reports only the columns it selects", func(t *testing.T) {
		result := c.ExecuteQuery(liveTabID, `SELECT name, price FROM specimens`, false)
		if !result.OK {
			t.Fatalf("query failed: %s", result.Message)
		}
		if len(result.ColumnTypes) != 2 {
			t.Fatalf("got %d column types, want 2", len(result.ColumnTypes))
		}
		if result.ColumnTypes[0].DataType != "text" || result.ColumnTypes[1].DataType != "numeric" {
			t.Errorf("got %q and %q, want text and numeric",
				result.ColumnTypes[0].DataType, result.ColumnTypes[1].DataType)
		}
	})

	t.Run("an expression is typed by its result", func(t *testing.T) {
		result := c.ExecuteQuery(liveTabID, `SELECT count(*) AS total, now() AS at FROM specimens`, false)
		if !result.OK {
			t.Fatalf("query failed: %s", result.Message)
		}
		if len(result.ColumnTypes) != 2 {
			t.Fatalf("got %d column types, want 2", len(result.ColumnTypes))
		}
		if result.ColumnTypes[0].DataType != "bigint" || result.ColumnTypes[0].Category != "N" {
			t.Errorf("count(*) = {%q %q}, want {bigint N}",
				result.ColumnTypes[0].DataType, result.ColumnTypes[0].Category)
		}
		if result.ColumnTypes[1].Category != "D" {
			t.Errorf("now() category = %q, want D", result.ColumnTypes[1].Category)
		}
	})

	t.Run("a single-column primary key is marked", func(t *testing.T) {
		result := c.ExecuteQuery(liveTabID, `SELECT * FROM specimens`, false)
		if !result.OK {
			t.Fatalf("query failed: %s", result.Message)
		}
		id := result.ColumnTypes[0]
		if !id.IsPrimaryKey {
			t.Errorf("id is not marked a primary key")
		}
		if id.IsCompositeKey {
			t.Errorf("id is marked a composite key, but it is the whole key")
		}
		if id.IsNullable {
			t.Errorf("id is marked nullable")
		}
		for _, columnType := range result.ColumnTypes[1:] {
			if columnType.IsPrimaryKey {
				t.Errorf("%q is marked a primary key", columnType.Name)
			}
		}
	})

	t.Run("a foreign key names the table it points at", func(t *testing.T) {
		result := c.ExecuteQuery(liveTabID, `SELECT keeper_id FROM specimens`, false)
		if !result.OK {
			t.Fatalf("query failed: %s", result.Message)
		}
		keeper := result.ColumnTypes[0]
		if !keeper.IsForeignKey {
			t.Fatalf("keeper_id is not marked a foreign key")
		}
		if keeper.ForeignKeyTable != "keepers" {
			t.Errorf("keeper_id references %q, want %q", keeper.ForeignKeyTable, "keepers")
		}
	})

	t.Run("every column of a composite primary key is marked", func(t *testing.T) {
		exec(t, c, `CREATE TABLE readings (
			specimen_id integer NOT NULL,
			taken_at timestamptz NOT NULL,
			value numeric,
			PRIMARY KEY (specimen_id, taken_at)
		)`)

		result := c.ExecuteQuery(liveTabID, `SELECT * FROM readings`, false)
		if !result.OK {
			t.Fatalf("query failed: %s", result.Message)
		}
		for i, want := range []bool{true, true, false} {
			got := result.ColumnTypes[i]
			if got.IsPrimaryKey != want || got.IsCompositeKey != want {
				t.Errorf("%q = {pk %v, composite %v}, want both %v",
					got.Name, got.IsPrimaryKey, got.IsCompositeKey, want)
			}
		}
	})

	t.Run("an expression has no column behind it to describe", func(t *testing.T) {
		// upper(name) is not a reference to a column, so postgres reports no
		// table for it and none of the key or nullability flags apply.
		result := c.ExecuteQuery(liveTabID, `SELECT upper(name) FROM specimens`, false)
		if !result.OK {
			t.Fatalf("query failed: %s", result.Message)
		}
		got := result.ColumnTypes[0]
		if got.DisplayType != "text" {
			t.Errorf("upper(name) display type = %q, want text", got.DisplayType)
		}
		if got.IsNullable || got.IsPrimaryKey || got.IsCompositeKey || got.IsForeignKey {
			t.Errorf("upper(name) carries column flags: %+v", got)
		}
	})

	t.Run("a write reports no column types", func(t *testing.T) {
		// The "Rows Affected" column has no table behind it, so there is nothing
		// to type and the header falls back to a plain label.
		result := c.ExecuteQuery(liveTabID, `INSERT INTO specimens (name) VALUES ('one')`, false)
		if !result.OK {
			t.Fatalf("insert failed: %s", result.Message)
		}
		if len(result.ColumnTypes) != 0 {
			t.Errorf("got %d column types, want none", len(result.ColumnTypes))
		}
	})
}
