package app

import (
	"context"
	"dbmx/model"
	"fmt"
	"regexp"
	"slices"
	"strings"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/pkg/errors"
)

// Schema editing, unlike row editing, cannot bind anything as a parameter: postgres
// has no parameter slots in DDL, so every identifier, type and expression is
// interpolated into the statement text. Identifiers therefore go through
// pgx.Identifier.Sanitize, and a type name is checked against the catalog with
// to_regtype before it is interpolated -- to_regtype parses the string with
// postgres' own type parser, so anything that is not a single well-formed type
// name is rejected rather than embedded.
//
// Default, generated, predicate and constraint expressions stay free-form, because
// that is what they are: arbitrary SQL the user is deliberately writing. Every
// statement below runs inside a transaction, so an operation that needs several
// statements (rename plus retype plus comment) either lands whole or not at all.

// A type name is parsed by postgres, but this cheap pre-filter runs first. It has to:
// to_regtype("text-- x") parses as plain text and reports valid, and interpolating
// that would comment out the rest of the statement it lands in. The class below holds
// exactly what a type name needs -- "character varying(255)", "numeric(10,2)",
// "text[]", "public.mood", `"My Type"` -- and nothing that starts a comment or ends a
// statement.
var typeNamePattern = regexp.MustCompile(`^[A-Za-z0-9_ ."\[\](),]+$`)

// Types worth putting at the top of a list of several hundred.
var commonTypeNames = map[string]bool{
	"bigint": true, "boolean": true, "bytea": true, "character": true,
	"character varying": true, "date": true, "double precision": true,
	"inet": true, "integer": true, "json": true, "jsonb": true, "numeric": true,
	"real": true, "smallint": true, "text": true, "time without time zone": true,
	"timestamp with time zone": true, "timestamp without time zone": true,
	"uuid": true,
}

// qualify renders a schema-qualified, quoted table name for interpolation.
func qualify(tableName string) string {
	return pgx.Identifier{"public", tableName}.Sanitize()
}

// validateTypeName checks that dataType is a single type postgres recognises, and
// returns it trimmed. The modifier is kept: to_regtype accepts "varchar(255)" and
// reports the base type, but the statement needs the modifier the user wrote.
func validateTypeName(ctx context.Context, pool *pgxpool.Pool, dataType string) (string, error) {
	trimmed := strings.TrimSpace(dataType)
	if trimmed == "" {
		return "", errors.New("a data type is required")
	}
	if !typeNamePattern.MatchString(trimmed) {
		return "", errors.Errorf("%q is not a valid type name", trimmed)
	}

	var oid *uint32
	// to_regtype raises a syntax error rather than returning NULL on some server
	// versions, so both outcomes are treated as "not a type".
	if err := pool.QueryRow(ctx, "SELECT to_regtype($1)::oid", trimmed).Scan(&oid); err != nil {
		return "", errors.Errorf("%q is not a type this database knows", trimmed)
	}
	if oid == nil {
		return "", errors.Errorf("%q is not a type this database knows", trimmed)
	}
	return trimmed, nil
}

// requireName rejects a blank identifier before it is quoted into a statement.
func requireName(kind, name string) (string, error) {
	trimmed := strings.TrimSpace(name)
	if trimmed == "" {
		return "", errors.Errorf("a %s name is required", kind)
	}
	return trimmed, nil
}

// identityClause renders the GENERATED ... AS IDENTITY fragment, or "" for none.
func identityClause(identity string) (string, error) {
	switch strings.ToUpper(strings.TrimSpace(identity)) {
	case "":
		return "", nil
	case "ALWAYS":
		return "GENERATED ALWAYS AS IDENTITY", nil
	case "BY DEFAULT":
		return "GENERATED BY DEFAULT AS IDENTITY", nil
	default:
		return "", errors.Errorf("identity must be ALWAYS or BY DEFAULT, got %q", identity)
	}
}

// execInTx runs statements in order inside one transaction, so a multi-statement
// edit never leaves the table half-changed.
func execInTx(ctx context.Context, pool *pgxpool.Pool, statements []string) error {
	if len(statements) == 0 {
		return nil
	}

	tx, err := pool.Begin(ctx)
	if err != nil {
		return err
	}
	defer tx.Rollback(ctx)

	for _, statement := range statements {
		if _, err := tx.Exec(ctx, statement); err != nil {
			return err
		}
	}

	return tx.Commit(ctx)
}

// GetSchemaEditorOptions returns the catalog-backed choices the column, index and
// constraint forms offer: every type the database can use (its own enums, domains
// and composites included), the index methods the server has installed, the
// collations, and the table names a foreign key can point at.
func (c *Connections) GetSchemaEditorOptions(tabID int64) (*model.SchemaEditorOptions, error) {
	pool, err := c.poolForTab(tabID)
	if err != nil {
		return nil, err
	}
	ctx := context.Background()

	options := &model.SchemaEditorOptions{
		Types:        []model.TypeOption{},
		IndexMethods: []string{},
		Collations:   []string{},
		Tables:       []string{},
	}

	// Array types are excluded: postgres generates one per base type, which would
	// triple the list for no gain when "text[]" is typed as a suffix instead.
	typeRows, err := pool.Query(ctx, `
		SELECT
			format_type(t.oid, NULL) AS name,
			CASE t.typtype
				WHEN 'e' THEN 'enum'
				WHEN 'd' THEN 'domain'
				WHEN 'r' THEN 'range'
				WHEN 'm' THEN 'range'
				WHEN 'c' THEN 'composite'
				ELSE 'base'
			END AS kind,
			n.nspname AS schema,
			CASE WHEN t.typtype = 'e' THEN ARRAY(
				SELECT e.enumlabel::text FROM pg_enum e
				WHERE e.enumtypid = t.oid ORDER BY e.enumsortorder
			) END AS enum_values,
			t.typmodin <> 0 AS accepts_modifier
		FROM pg_type t
		JOIN pg_namespace n ON n.oid = t.typnamespace
		WHERE t.typtype IN ('b', 'e', 'd', 'r', 'm', 'c')
			AND t.typelem = 0
			AND (t.typrelid = 0 OR (SELECT c.relkind FROM pg_class c WHERE c.oid = t.typrelid) = 'c')
			AND n.nspname <> 'pg_toast'
			AND pg_type_is_visible(t.oid)
		ORDER BY 1
	`)
	if err != nil {
		return nil, err
	}
	defer typeRows.Close()

	for typeRows.Next() {
		var (
			option     model.TypeOption
			enumValues []string
		)
		if err := typeRows.Scan(
			&option.Name, &option.Kind, &option.Schema, &enumValues, &option.AcceptsModifier,
		); err != nil {
			return nil, err
		}
		option.EnumValues = enumValues
		option.IsCommon = commonTypeNames[option.Name]
		options.Types = append(options.Types, option)
	}
	if err := typeRows.Err(); err != nil {
		return nil, err
	}

	options.IndexMethods, err = indexMethods(ctx, pool)
	if err != nil {
		return nil, err
	}

	collationRows, err := pool.Query(ctx, `
		SELECT DISTINCT collname
		FROM pg_collation
		WHERE collencoding IN (-1, pg_char_to_encoding(current_setting('server_encoding')))
		ORDER BY collname
	`)
	if err != nil {
		return nil, err
	}
	defer collationRows.Close()
	for collationRows.Next() {
		var collation string
		if err := collationRows.Scan(&collation); err != nil {
			return nil, err
		}
		options.Collations = append(options.Collations, collation)
	}
	if err := collationRows.Err(); err != nil {
		return nil, err
	}

	tableRows, err := pool.Query(ctx, `
		SELECT relname
		FROM pg_class c
		JOIN pg_namespace n ON n.oid = c.relnamespace
		WHERE n.nspname = 'public' AND c.relkind IN ('r', 'p')
		ORDER BY relname
	`)
	if err != nil {
		return nil, err
	}
	defer tableRows.Close()
	for tableRows.Next() {
		var table string
		if err := tableRows.Scan(&table); err != nil {
			return nil, err
		}
		options.Tables = append(options.Tables, table)
	}
	if err := tableRows.Err(); err != nil {
		return nil, err
	}

	return options, nil
}

// indexMethods lists the index access methods this server has installed.
func indexMethods(ctx context.Context, pool *pgxpool.Pool) ([]string, error) {
	rows, err := pool.Query(ctx, `SELECT amname FROM pg_am WHERE amtype = 'i' ORDER BY amname`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	methods := []string{}
	for rows.Next() {
		var method string
		if err := rows.Scan(&method); err != nil {
			return nil, err
		}
		methods = append(methods, method)
	}

	return methods, rows.Err()
}

// GetColumnDefinition returns one column in the shape the edit form works with.
func (c *Connections) GetColumnDefinition(tabID int64, tableName, columnName string) (*model.ColumnDefinition, error) {
	pool, err := c.poolForTab(tabID)
	if err != nil {
		return nil, err
	}

	var (
		def          model.ColumnDefinition
		attnotnull   bool
		defaultValue *string
		identity     string
		generated    string
		collation    *string
		comment      *string
	)
	err = pool.QueryRow(context.Background(), `
		SELECT
			a.attname,
			format_type(a.atttypid, a.atttypmod),
			a.attnotnull,
			pg_get_expr(ad.adbin, ad.adrelid),
			a.attidentity::text,
			a.attgenerated::text,
			(SELECT collname FROM pg_collation WHERE oid = a.attcollation AND a.attcollation <> t.typcollation),
			col_description(a.attrelid, a.attnum),
			COALESCE((
				SELECT true FROM pg_index i
				WHERE i.indrelid = a.attrelid AND i.indisprimary AND a.attnum = ANY(i.indkey)
			), false)
		FROM pg_attribute a
		JOIN pg_type t ON t.oid = a.atttypid
		LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
		WHERE a.attrelid = $1::regclass
			AND a.attname = $2
			AND a.attnum > 0
			AND NOT a.attisdropped
	`, qualify(tableName), columnName).Scan(
		&def.Name,
		&def.DataType,
		&attnotnull,
		&defaultValue,
		&identity,
		&generated,
		&collation,
		&comment,
		&def.IsPrimaryKey,
	)
	if err != nil {
		return nil, errors.Wrapf(err, "column %q not found on %q", columnName, tableName)
	}

	def.IsNullable = !attnotnull
	// A generated column stores its expression in pg_attrdef too, so the same text
	// is either the default or the generation expression, never both.
	if generated != "" {
		if defaultValue != nil {
			def.GeneratedExpression = *defaultValue
		}
	} else if defaultValue != nil {
		def.DefaultValue = *defaultValue
	}
	switch identity {
	case "a":
		def.Identity = "ALWAYS"
	case "d":
		def.Identity = "BY DEFAULT"
	}
	if collation != nil {
		def.Collation = *collation
	}
	if comment != nil {
		def.Comment = *comment
	}

	return &def, nil
}

// AddColumn appends a column to tableName.
//
// A NOT NULL column added to a table that already has rows needs a default (or an
// identity, or a generation expression) for those rows to satisfy it; postgres
// reports that itself, so it is not second-guessed here.
func (c *Connections) AddColumn(tabID int64, tableName string, def model.ColumnDefinition) error {
	pool, err := c.poolForTab(tabID)
	if err != nil {
		return err
	}
	ctx := context.Background()

	name, err := requireName("column", def.Name)
	if err != nil {
		return err
	}
	dataType, err := validateTypeName(ctx, pool, def.DataType)
	if err != nil {
		return err
	}
	identity, err := identityClause(def.Identity)
	if err != nil {
		return err
	}

	generated := strings.TrimSpace(def.GeneratedExpression)
	defaultValue := strings.TrimSpace(def.DefaultValue)
	if generated != "" && (defaultValue != "" || identity != "") {
		return errors.New("a generated column cannot also have a default or an identity")
	}
	if defaultValue != "" && identity != "" {
		return errors.New("an identity column cannot also have a default")
	}

	parts := []string{
		fmt.Sprintf(
			"ALTER TABLE %s ADD COLUMN %s %s",
			qualify(tableName),
			pgx.Identifier{name}.Sanitize(),
			dataType,
		),
	}
	if collation := strings.TrimSpace(def.Collation); collation != "" {
		parts = append(parts, "COLLATE "+pgx.Identifier{collation}.Sanitize())
	}
	if generated != "" {
		parts = append(parts, fmt.Sprintf("GENERATED ALWAYS AS (%s) STORED", generated))
	}
	if identity != "" {
		parts = append(parts, identity)
	}
	if defaultValue != "" {
		parts = append(parts, "DEFAULT "+defaultValue)
	}
	if !def.IsNullable {
		parts = append(parts, "NOT NULL")
	}

	statements := []string{strings.Join(parts, " ")}
	statements = append(statements, commentStatement(
		"COLUMN",
		qualify(tableName)+"."+pgx.Identifier{name}.Sanitize(),
		def.Comment,
	))

	return execInTx(ctx, pool, statements)
}

// UpdateColumn applies the difference between the column named originalName and
// def, as the smallest set of ALTER sub-commands that expresses it.
//
// The rename goes first so every later sub-command can address the column by its
// new name, and the whole set runs in one transaction: renaming a column and then
// failing to retype it would otherwise leave the table in a state the user never
// asked for.
func (c *Connections) UpdateColumn(tabID int64, tableName, originalName string, def model.ColumnDefinition) error {
	pool, err := c.poolForTab(tabID)
	if err != nil {
		return err
	}
	ctx := context.Background()

	current, err := c.GetColumnDefinition(tabID, tableName, originalName)
	if err != nil {
		return err
	}

	name, err := requireName("column", def.Name)
	if err != nil {
		return err
	}
	dataType, err := validateTypeName(ctx, pool, def.DataType)
	if err != nil {
		return err
	}
	identity, err := identityClause(def.Identity)
	if err != nil {
		return err
	}

	generated := strings.TrimSpace(def.GeneratedExpression)
	if generated != current.GeneratedExpression && generated != "" {
		// Postgres has no ALTER COLUMN ... SET EXPRESSION before 17, and this is a
		// clearer message than the syntax error the server would return.
		return errors.New(
			"a generated column's expression cannot be changed in place; drop the column and add it again",
		)
	}

	safeTable := qualify(tableName)
	safeColumn := pgx.Identifier{name}.Sanitize()
	var statements []string

	if name != current.Name {
		statements = append(statements, fmt.Sprintf(
			"ALTER TABLE %s RENAME COLUMN %s TO %s",
			safeTable, pgx.Identifier{current.Name}.Sanitize(), safeColumn,
		))
	}

	// A collation change is also expressed as a TYPE sub-command -- retyping to the
	// same type with a new COLLATE is how postgres spells it -- and clearing the box
	// emits the type on its own, which restores the type's default collation.
	if dataType != current.DataType || strings.TrimSpace(def.Collation) != current.Collation {
		alter := fmt.Sprintf("ALTER TABLE %s ALTER COLUMN %s TYPE %s", safeTable, safeColumn, dataType)
		if collation := strings.TrimSpace(def.Collation); collation != "" {
			alter += " COLLATE " + pgx.Identifier{collation}.Sanitize()
		}
		if using := strings.TrimSpace(def.UsingExpression); using != "" {
			alter += " USING " + using
		}
		statements = append(statements, alter)
	}

	if generated == "" && current.GeneratedExpression != "" {
		statements = append(statements, fmt.Sprintf(
			"ALTER TABLE %s ALTER COLUMN %s DROP EXPRESSION", safeTable, safeColumn,
		))
	}

	if def.Identity != current.Identity {
		switch {
		case identity == "":
			statements = append(statements, fmt.Sprintf(
				"ALTER TABLE %s ALTER COLUMN %s DROP IDENTITY IF EXISTS", safeTable, safeColumn,
			))
		case current.Identity == "":
			statements = append(statements, fmt.Sprintf(
				"ALTER TABLE %s ALTER COLUMN %s ADD %s", safeTable, safeColumn, identity,
			))
		default:
			// ADD takes "GENERATED ALWAYS AS IDENTITY"; SET takes only the
			// "GENERATED ALWAYS" head, so the tail is trimmed off here.
			statements = append(statements, fmt.Sprintf(
				"ALTER TABLE %s ALTER COLUMN %s SET %s", safeTable, safeColumn,
				strings.TrimSuffix(identity, " AS IDENTITY"),
			))
		}
	}

	defaultValue := strings.TrimSpace(def.DefaultValue)
	if defaultValue != current.DefaultValue {
		if defaultValue == "" {
			statements = append(statements, fmt.Sprintf(
				"ALTER TABLE %s ALTER COLUMN %s DROP DEFAULT", safeTable, safeColumn,
			))
		} else {
			statements = append(statements, fmt.Sprintf(
				"ALTER TABLE %s ALTER COLUMN %s SET DEFAULT %s", safeTable, safeColumn, defaultValue,
			))
		}
	}

	if def.IsNullable != current.IsNullable {
		action := "SET NOT NULL"
		if def.IsNullable {
			action = "DROP NOT NULL"
		}
		statements = append(statements, fmt.Sprintf(
			"ALTER TABLE %s ALTER COLUMN %s %s", safeTable, safeColumn, action,
		))
	}

	if comment := strings.TrimSpace(def.Comment); comment != current.Comment {
		statements = append(statements, commentStatement("COLUMN", safeTable+"."+safeColumn, comment))
	}

	if len(statements) == 0 {
		return errors.New("nothing to change")
	}

	return execInTx(ctx, pool, statements)
}

// DropColumn removes a column. Without cascade postgres refuses while anything --
// a view, an index, a foreign key -- still depends on it, which is the safer default.
func (c *Connections) DropColumn(tabID int64, tableName, columnName string, cascade bool) error {
	pool, err := c.poolForTab(tabID)
	if err != nil {
		return err
	}

	name, err := requireName("column", columnName)
	if err != nil {
		return err
	}

	statement := fmt.Sprintf(
		"ALTER TABLE %s DROP COLUMN %s %s",
		qualify(tableName),
		pgx.Identifier{name}.Sanitize(),
		cascadeClause(cascade),
	)

	return execInTx(context.Background(), pool, []string{statement})
}

// GetIndexDefinition returns one index as structured parts. Each key expression is
// rendered by pg_get_indexdef column by column, so operator classes, collations and
// ordering survive a round trip that parsing the whole statement would lose.
func (c *Connections) GetIndexDefinition(tabID int64, tableName, indexName string) (*model.IndexDefinition, error) {
	pool, err := c.poolForTab(tabID)
	if err != nil {
		return nil, err
	}
	ctx := context.Background()

	var (
		def        model.IndexDefinition
		keyAtts    int
		totalAtts  int
		predicate  *string
		comment    *string
		constraint *string
	)
	err = pool.QueryRow(ctx, `
		SELECT
			ic.relname,
			am.amname,
			i.indisunique,
			i.indisprimary,
			i.indnkeyatts,
			i.indnatts,
			pg_get_expr(i.indpred, i.indrelid),
			obj_description(i.indexrelid, 'pg_class'),
			(SELECT conname FROM pg_constraint WHERE conindid = i.indexrelid LIMIT 1)
		FROM pg_index i
		JOIN pg_class ic ON ic.oid = i.indexrelid
		JOIN pg_am am ON am.oid = ic.relam
		WHERE i.indrelid = $1::regclass AND ic.relname = $2
	`, qualify(tableName), indexName).Scan(
		&def.Name,
		&def.Method,
		&def.IsUnique,
		&def.IsPrimary,
		&keyAtts,
		&totalAtts,
		&predicate,
		&comment,
		&constraint,
	)
	if err != nil {
		return nil, errors.Wrapf(err, "index %q not found on %q", indexName, tableName)
	}

	def.IsConstraint = constraint != nil
	if predicate != nil {
		def.Where = *predicate
	}
	if comment != nil {
		def.Comment = *comment
	}

	def.Columns = []string{}
	def.Include = []string{}
	for position := 1; position <= totalAtts; position++ {
		var expression string
		if err := pool.QueryRow(
			ctx, "SELECT pg_get_indexdef($1::regclass, $2, true)",
			pgx.Identifier{"public", def.Name}.Sanitize(), position,
		).Scan(&expression); err != nil {
			return nil, err
		}
		if position <= keyAtts {
			def.Columns = append(def.Columns, expression)
		} else {
			def.Include = append(def.Include, expression)
		}
	}

	return &def, nil
}

// buildCreateIndex renders a CREATE INDEX for def. The key and include entries are
// expressions the user wrote or postgres rendered, so they are interpolated as
// given; the name, method and table are quoted or checked.
func buildCreateIndex(tableName string, def model.IndexDefinition, methods []string) (string, error) {
	name, err := requireName("index", def.Name)
	if err != nil {
		return "", err
	}

	method := strings.TrimSpace(def.Method)
	if method == "" {
		method = "btree"
	}
	if !slices.Contains(methods, method) {
		return "", errors.Errorf("%q is not an index method this database has", method)
	}

	columns := trimmedNonEmpty(def.Columns)
	if len(columns) == 0 {
		return "", errors.New("an index needs at least one column")
	}

	unique := ""
	if def.IsUnique {
		unique = "UNIQUE "
	}

	statement := fmt.Sprintf(
		"CREATE %sINDEX %s ON %s USING %s (%s)",
		unique,
		pgx.Identifier{name}.Sanitize(),
		qualify(tableName),
		pgx.Identifier{method}.Sanitize(),
		strings.Join(columns, ", "),
	)
	if include := trimmedNonEmpty(def.Include); len(include) > 0 {
		statement += fmt.Sprintf(" INCLUDE (%s)", strings.Join(include, ", "))
	}
	if where := strings.TrimSpace(def.Where); where != "" {
		statement += " WHERE " + where
	}

	return statement, nil
}

// CreateIndex adds an index to tableName.
func (c *Connections) CreateIndex(tabID int64, tableName string, def model.IndexDefinition) error {
	pool, err := c.poolForTab(tabID)
	if err != nil {
		return err
	}

	methods, err := indexMethods(context.Background(), pool)
	if err != nil {
		return err
	}

	statement, err := buildCreateIndex(tableName, def, methods)
	if err != nil {
		return err
	}

	statements := []string{statement}
	statements = append(statements, commentStatement(
		"INDEX",
		pgx.Identifier{"public", strings.TrimSpace(def.Name)}.Sanitize(),
		def.Comment,
	))

	return execInTx(context.Background(), pool, statements)
}

// UpdateIndex applies def to the index named originalName.
//
// Postgres can only rename an index, not redefine one, so anything beyond a rename
// is a drop and a create -- run in one transaction, which means a create that fails
// leaves the original index in place rather than the table unindexed.
func (c *Connections) UpdateIndex(tabID int64, tableName, originalName string, def model.IndexDefinition) error {
	pool, err := c.poolForTab(tabID)
	if err != nil {
		return err
	}

	current, err := c.GetIndexDefinition(tabID, tableName, originalName)
	if err != nil {
		return err
	}
	if current.IsConstraint {
		return errors.Errorf(
			"%q backs a constraint, so it cannot be edited as an index -- edit the constraint under Rules instead",
			originalName,
		)
	}

	name, err := requireName("index", def.Name)
	if err != nil {
		return err
	}

	methods, err := indexMethods(context.Background(), pool)
	if err != nil {
		return err
	}

	renamedOnly := name != current.Name &&
		def.IsUnique == current.IsUnique &&
		strings.TrimSpace(def.Method) == current.Method &&
		equalExpressions(def.Columns, current.Columns) &&
		equalExpressions(def.Include, current.Include) &&
		strings.TrimSpace(def.Where) == current.Where

	var statements []string
	switch {
	case renamedOnly:
		statements = append(statements, fmt.Sprintf(
			"ALTER INDEX %s RENAME TO %s",
			pgx.Identifier{"public", current.Name}.Sanitize(),
			pgx.Identifier{name}.Sanitize(),
		))
	default:
		created, err := buildCreateIndex(tableName, def, methods)
		if err != nil {
			return err
		}
		statements = append(statements,
			fmt.Sprintf("DROP INDEX %s", pgx.Identifier{"public", current.Name}.Sanitize()),
			created,
		)
	}

	// A rebuilt index is a new object and has lost the old one's comment, so the
	// comment is always rewritten unless this was only a rename.
	if comment := strings.TrimSpace(def.Comment); comment != current.Comment || !renamedOnly {
		statements = append(statements, commentStatement(
			"INDEX", pgx.Identifier{"public", name}.Sanitize(), comment,
		))
	}

	return execInTx(context.Background(), pool, statements)
}

// DropIndex removes an index. An index postgres created for a constraint is
// refused here, because dropping it would have to go through the constraint.
func (c *Connections) DropIndex(tabID int64, tableName, indexName string, cascade bool) error {
	pool, err := c.poolForTab(tabID)
	if err != nil {
		return err
	}

	current, err := c.GetIndexDefinition(tabID, tableName, indexName)
	if err != nil {
		return err
	}
	if current.IsConstraint {
		return errors.Errorf(
			"%q backs a constraint, so it cannot be dropped as an index -- drop the constraint under Rules instead",
			indexName,
		)
	}

	statement := fmt.Sprintf(
		"DROP INDEX %s %s",
		pgx.Identifier{"public", current.Name}.Sanitize(),
		cascadeClause(cascade),
	)

	return execInTx(context.Background(), pool, []string{statement})
}

// GetConstraintDefinition returns one constraint with its body exactly as postgres
// renders it, which is also the text ALTER TABLE ... ADD CONSTRAINT accepts back.
func (c *Connections) GetConstraintDefinition(tabID int64, tableName, constraintName string) (*model.ConstraintDefinition, error) {
	pool, err := c.poolForTab(tabID)
	if err != nil {
		return nil, err
	}

	var (
		def     model.ConstraintDefinition
		comment *string
	)
	err = pool.QueryRow(context.Background(), `
		SELECT
			con.conname,
			CASE con.contype
				WHEN 'p' THEN 'PRIMARY KEY'
				WHEN 'u' THEN 'UNIQUE'
				WHEN 'f' THEN 'FOREIGN KEY'
				WHEN 'c' THEN 'CHECK'
				WHEN 'x' THEN 'EXCLUDE'
				ELSE con.contype::text
			END,
			pg_get_constraintdef(con.oid),
			con.convalidated,
			obj_description(con.oid, 'pg_constraint')
		FROM pg_constraint con
		WHERE con.conrelid = $1::regclass AND con.conname = $2
	`, qualify(tableName), constraintName).Scan(
		&def.Name,
		&def.Type,
		&def.Definition,
		&def.IsValidated,
		&comment,
	)
	if err != nil {
		return nil, errors.Wrapf(err, "constraint %q not found on %q", constraintName, tableName)
	}

	// pg_get_constraintdef appends NOT VALID to the body; it is carried as a flag so
	// the form can offer it as a checkbox rather than as text to hand-edit.
	if body, found := strings.CutSuffix(def.Definition, " NOT VALID"); found {
		def.Definition = body
		def.NotValid = true
	}
	if comment != nil {
		def.Comment = *comment
	}

	return &def, nil
}

// buildAddConstraint renders an ALTER TABLE ... ADD CONSTRAINT for def.
func buildAddConstraint(tableName string, def model.ConstraintDefinition) (string, error) {
	name, err := requireName("constraint", def.Name)
	if err != nil {
		return "", err
	}

	body := strings.TrimSpace(def.Definition)
	if body == "" {
		return "", errors.New("a constraint definition is required")
	}

	statement := fmt.Sprintf(
		"ALTER TABLE %s ADD CONSTRAINT %s %s",
		qualify(tableName),
		pgx.Identifier{name}.Sanitize(),
		body,
	)
	// NOT VALID applies to CHECK and FOREIGN KEY only; postgres rejects it elsewhere.
	if def.NotValid && (def.Type == "CHECK" || def.Type == "FOREIGN KEY") {
		statement += " NOT VALID"
	}

	return statement, nil
}

// AddConstraint adds a constraint to tableName.
func (c *Connections) AddConstraint(tabID int64, tableName string, def model.ConstraintDefinition) error {
	pool, err := c.poolForTab(tabID)
	if err != nil {
		return err
	}

	statement, err := buildAddConstraint(tableName, def)
	if err != nil {
		return err
	}

	statements := []string{statement}
	statements = append(statements, commentStatement(
		"CONSTRAINT",
		pgx.Identifier{strings.TrimSpace(def.Name)}.Sanitize()+" ON "+qualify(tableName),
		def.Comment,
	))

	return execInTx(context.Background(), pool, statements)
}

// UpdateConstraint applies def to the constraint named originalName.
//
// As with indexes, only a rename can be done in place. Changing the body is a drop
// and an add in one transaction, so a body postgres rejects -- a CHECK the existing
// rows fail, a foreign key with no matching parent -- leaves the original standing.
func (c *Connections) UpdateConstraint(tabID int64, tableName, originalName string, def model.ConstraintDefinition) error {
	pool, err := c.poolForTab(tabID)
	if err != nil {
		return err
	}

	current, err := c.GetConstraintDefinition(tabID, tableName, originalName)
	if err != nil {
		return err
	}

	name, err := requireName("constraint", def.Name)
	if err != nil {
		return err
	}

	bodyUnchanged := strings.TrimSpace(def.Definition) == current.Definition &&
		def.NotValid == current.NotValid
	safeTable := qualify(tableName)

	var statements []string
	if bodyUnchanged {
		if name != current.Name {
			statements = append(statements, fmt.Sprintf(
				"ALTER TABLE %s RENAME CONSTRAINT %s TO %s",
				safeTable,
				pgx.Identifier{current.Name}.Sanitize(),
				pgx.Identifier{name}.Sanitize(),
			))
		}
	} else {
		added, err := buildAddConstraint(tableName, def)
		if err != nil {
			return err
		}
		statements = append(statements, fmt.Sprintf(
			"ALTER TABLE %s DROP CONSTRAINT %s",
			safeTable, pgx.Identifier{current.Name}.Sanitize(),
		), added)
	}

	// As with an index, a replaced constraint is a new object without the old
	// comment, so it is rewritten unless this was only a rename.
	if comment := strings.TrimSpace(def.Comment); comment != current.Comment || !bodyUnchanged {
		statements = append(statements, commentStatement(
			"CONSTRAINT",
			pgx.Identifier{name}.Sanitize()+" ON "+safeTable,
			comment,
		))
	}

	if len(statements) == 0 {
		return errors.New("nothing to change")
	}

	return execInTx(context.Background(), pool, statements)
}

// DropConstraint removes a constraint. Dropping a primary or unique constraint also
// drops the index behind it, and cascade additionally drops any foreign key pointing
// at it.
func (c *Connections) DropConstraint(tabID int64, tableName, constraintName string, cascade bool) error {
	pool, err := c.poolForTab(tabID)
	if err != nil {
		return err
	}

	name, err := requireName("constraint", constraintName)
	if err != nil {
		return err
	}

	statement := fmt.Sprintf(
		"ALTER TABLE %s DROP CONSTRAINT %s %s",
		qualify(tableName),
		pgx.Identifier{name}.Sanitize(),
		cascadeClause(cascade),
	)

	return execInTx(context.Background(), pool, []string{statement})
}

// commentStatement renders COMMENT ON for target. An empty comment sets NULL, which
// is how postgres removes one, so the same statement both writes and clears.
func commentStatement(kind, target, comment string) string {
	value := "NULL"
	if trimmed := strings.TrimSpace(comment); trimmed != "" {
		value = quoteSQLLiteral(trimmed)
	}
	return fmt.Sprintf("COMMENT ON %s %s IS %s", kind, target, value)
}

func cascadeClause(cascade bool) string {
	if cascade {
		return "CASCADE"
	}
	return "RESTRICT"
}

func trimmedNonEmpty(values []string) []string {
	result := make([]string, 0, len(values))
	for _, value := range values {
		if trimmed := strings.TrimSpace(value); trimmed != "" {
			result = append(result, trimmed)
		}
	}
	return result
}

func equalExpressions(left, right []string) bool {
	leftTrimmed, rightTrimmed := trimmedNonEmpty(left), trimmedNonEmpty(right)
	if len(leftTrimmed) != len(rightTrimmed) {
		return false
	}
	for i := range leftTrimmed {
		if leftTrimmed[i] != rightTrimmed[i] {
			return false
		}
	}
	return true
}
